POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vdXNlIiwiaWQiOiI1ZmM5MGY3MzFiNzY1ZDEzMTFiZWNhZGEiLCJpYXQiOjE2MDcwMTQxODd9.geXCFFIM7Xl6LYKXldxDZlS_uaFceOQAgM7-nKj0R80

{
    "title": "Hi there",
    "author": "XYZ",
    "url": "www.helloworld.com"
}